// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGKnigqgugBqA6-g1FeScfZFnQeQBvUcM',
    appId: '1:460793056283:web:05cea5ade9aec818363cbe',
    messagingSenderId: '460793056283',
    projectId: 'vshop-ab506',
    authDomain: 'vshop-ab506.firebaseapp.com',
    storageBucket: 'vshop-ab506.firebasestorage.app',
    measurementId: 'G-RMBEVY3N02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxQopU5wuXrFRDekj18xWhYIZEAktOZt8',
    appId: '1:460793056283:android:e9211c85bc8997f1363cbe',
    messagingSenderId: '460793056283',
    projectId: 'vshop-ab506',
    storageBucket: 'vshop-ab506.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwez5LzLuqAeeKZAQyB9TIxctSm_QoMco',
    appId: '1:460793056283:ios:bb1a7740f4354f64363cbe',
    messagingSenderId: '460793056283',
    projectId: 'vshop-ab506',
    storageBucket: 'vshop-ab506.firebasestorage.app',
    iosBundleId: 'com.example.vshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwez5LzLuqAeeKZAQyB9TIxctSm_QoMco',
    appId: '1:460793056283:ios:bb1a7740f4354f64363cbe',
    messagingSenderId: '460793056283',
    projectId: 'vshop-ab506',
    storageBucket: 'vshop-ab506.firebasestorage.app',
    iosBundleId: 'com.example.vshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGKnigqgugBqA6-g1FeScfZFnQeQBvUcM',
    appId: '1:460793056283:web:f3f0a99d4dd2e8b5363cbe',
    messagingSenderId: '460793056283',
    projectId: 'vshop-ab506',
    authDomain: 'vshop-ab506.firebaseapp.com',
    storageBucket: 'vshop-ab506.firebasestorage.app',
    measurementId: 'G-36CQ6J7LEC',
  );

}